/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.unicamp.prefeitura.springkafka;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class People extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6978620255954420741L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"People\",\"namespace\":\"br.unicamp.prefeitura.springkafka\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"cpf\",\"type\":\"string\"},{\"name\":\"books\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<People> ENCODER =
      new BinaryMessageEncoder<People>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<People> DECODER =
      new BinaryMessageDecoder<People>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<People> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<People> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<People> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<People>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this People to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a People from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a People instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static People fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence name;
  private java.lang.CharSequence cpf;
  private java.util.List<java.lang.CharSequence> books;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public People() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param cpf The new value for cpf
   * @param books The new value for books
   */
  public People(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.CharSequence cpf, java.util.List<java.lang.CharSequence> books) {
    this.id = id;
    this.name = name;
    this.cpf = cpf;
    this.books = books;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return cpf;
    case 3: return books;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: cpf = (java.lang.CharSequence)value$; break;
    case 3: books = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'cpf' field.
   * @return The value of the 'cpf' field.
   */
  public java.lang.CharSequence getCpf() {
    return cpf;
  }


  /**
   * Sets the value of the 'cpf' field.
   * @param value the value to set.
   */
  public void setCpf(java.lang.CharSequence value) {
    this.cpf = value;
  }

  /**
   * Gets the value of the 'books' field.
   * @return The value of the 'books' field.
   */
  public java.util.List<java.lang.CharSequence> getBooks() {
    return books;
  }


  /**
   * Sets the value of the 'books' field.
   * @param value the value to set.
   */
  public void setBooks(java.util.List<java.lang.CharSequence> value) {
    this.books = value;
  }

  /**
   * Creates a new People RecordBuilder.
   * @return A new People RecordBuilder
   */
  public static br.unicamp.prefeitura.springkafka.People.Builder newBuilder() {
    return new br.unicamp.prefeitura.springkafka.People.Builder();
  }

  /**
   * Creates a new People RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new People RecordBuilder
   */
  public static br.unicamp.prefeitura.springkafka.People.Builder newBuilder(br.unicamp.prefeitura.springkafka.People.Builder other) {
    if (other == null) {
      return new br.unicamp.prefeitura.springkafka.People.Builder();
    } else {
      return new br.unicamp.prefeitura.springkafka.People.Builder(other);
    }
  }

  /**
   * Creates a new People RecordBuilder by copying an existing People instance.
   * @param other The existing instance to copy.
   * @return A new People RecordBuilder
   */
  public static br.unicamp.prefeitura.springkafka.People.Builder newBuilder(br.unicamp.prefeitura.springkafka.People other) {
    if (other == null) {
      return new br.unicamp.prefeitura.springkafka.People.Builder();
    } else {
      return new br.unicamp.prefeitura.springkafka.People.Builder(other);
    }
  }

  /**
   * RecordBuilder for People instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<People>
    implements org.apache.avro.data.RecordBuilder<People> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence cpf;
    private java.util.List<java.lang.CharSequence> books;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.unicamp.prefeitura.springkafka.People.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.cpf)) {
        this.cpf = data().deepCopy(fields()[2].schema(), other.cpf);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.books)) {
        this.books = data().deepCopy(fields()[3].schema(), other.books);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing People instance
     * @param other The existing instance to copy.
     */
    private Builder(br.unicamp.prefeitura.springkafka.People other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cpf)) {
        this.cpf = data().deepCopy(fields()[2].schema(), other.cpf);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.books)) {
        this.books = data().deepCopy(fields()[3].schema(), other.books);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cpf' field.
      * @return The value.
      */
    public java.lang.CharSequence getCpf() {
      return cpf;
    }


    /**
      * Sets the value of the 'cpf' field.
      * @param value The value of 'cpf'.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder setCpf(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.cpf = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cpf' field has been set.
      * @return True if the 'cpf' field has been set, false otherwise.
      */
    public boolean hasCpf() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cpf' field.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder clearCpf() {
      cpf = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'books' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getBooks() {
      return books;
    }


    /**
      * Sets the value of the 'books' field.
      * @param value The value of 'books'.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder setBooks(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.books = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'books' field has been set.
      * @return True if the 'books' field has been set, false otherwise.
      */
    public boolean hasBooks() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'books' field.
      * @return This builder.
      */
    public br.unicamp.prefeitura.springkafka.People.Builder clearBooks() {
      books = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public People build() {
      try {
        People record = new People();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.cpf = fieldSetFlags()[2] ? this.cpf : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.books = fieldSetFlags()[3] ? this.books : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<People>
    WRITER$ = (org.apache.avro.io.DatumWriter<People>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<People>
    READER$ = (org.apache.avro.io.DatumReader<People>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.name);

    out.writeString(this.cpf);

    long size0 = this.books.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.books) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.cpf = in.readString(this.cpf instanceof Utf8 ? (Utf8)this.cpf : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.books;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("books").schema());
        this.books = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.cpf = in.readString(this.cpf instanceof Utf8 ? (Utf8)this.cpf : null);
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.books;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("books").schema());
            this.books = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










